version: "3"

services:

services:
  discord-soundbot:
    container_name: discord.soundbot
    image: aliart/discord-soundbot
    build:
      context: ./docker
      args:
        DOCKER_UID: ${DOCKER_UID}
        DOCKER_GID: ${DOCKER_GID}
        NODE_ENV: ${NODE_ENV}
        USERNAME: discord-soundbot
    volumes:
      - ./app:/app/
    networks:
      - discord-soundbot

networks:
  discord-soundbot:
      name: discord-soundbot
